services:
  headless:
    container_name: resonite-headless
    image: ghcr.io/voxelbonecloud/resonite-headless-docker:main 
    env_file: .env
    environment:
      CONFIG_FILE: Config.json
      ENABLE_MODS: false
      #ADDITIONAL_ARGUMENTS:
    tty: true
    stdin_open: true
    user: "1000:1000"
    volumes:
      - "Headless_Configs:/Config"
      - "Headless_Logs:/Logs"
      - "RML:/RML"
    restart: on-failure:5
volumes:
  Headless_Configs:
  Headless_Logs:
  RML:
