services:
  headless:
    container_name: resonite-headless
    image: ghcr.io/voxelbonecloud/resonite-headless-docker:main 
    environment:
      CONFIG_FILE: Config.json
      # ADDITIONAL_ARGUMENTS:
      STEAM_USER: YourSteamUsername
      STEAM_PASS: YourSteamPassword
      BETA_CODE: SteamBetaCode
      STEAM_BRANCH: headless
      LOG_RETENTION: 30
      ENABLE_MODS: false
    tty: true
    stdin_open: true
    user: "1000:1000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "Headless_Configs:/Config"
      - "Headless_Logs:/Logs"
      - "RML:/RML"
    restart: on-failure:5
volumes:
  Headless_Configs:
  Headless_Logs:
  RML:
