services:
  headless:
    container_name: resonite-headless
    image: ghcr.io/voxelbonecloud/resonite-headless-docker:main 
    env_file: .env
    environment:
      CONFIG_FILE: Config.json
      ENABLE_MODS: false
      # ADDITIONAL_ARGUMENTS:
    tty: true
    stdin_open: true
    user: "1000:1000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/path/to/Config:/Config"
      - "/path/to/Logs:/Logs"
      - "/path/to/RML:/RML" # This line can be removed if not using mods.
    restart: on-failure:5
